### ISSUE TITLE
How to run migrations

### ISSUE THREAD

**Issue by codebrewtest** [gecche/laravel-multidomain#25] opened 2020-05-02 07:12 UTC
I want some modification into the table then how to update table for all domain

**Comment by gecche** [comment] 2020-05-02 08:46
Hi,

it is not possible to run an artisan command for all domains at once.
The only way would be a "like-artisan" shell script as detailed extensively in #14. Note that this is not a bug but it is due to how the environment is handled by Laravel (and there is nothing wrong in that).

To date you have to run a migrate command for each domain, unless you want to contribute to such a script :)

Cheers 

Giacomo

P.S.: I close the issue as already addressed... if you liked the package please leave a star if you haven't done yet! ;)

**Closed by gecche** 2020-05-02 08:46 UTC
